array
  title Symbolic array
  cells 5 8 ... 34
  axis vertical
  index bottom reverse
  ptr head -> 0     "start of the run"
  ptr tail -> clast "last live element"
  ptr probe -> cgap "somewhere in the middle"
