/**
 * esbuild bundle for the Triton VS Code extension.
 *
 * Bundles `extension/src/extension.ts` plus the entire Triton compiler graph
 * (imported by relative path from `../src/**`) into a single CommonJS file at
 * `extension/dist/extension.cjs`. The VS Code extension host loads this via
 * `require()`, so the output MUST be CJS and `vscode` MUST stay external (it is
 * provided by the host and can never be bundled).
 *
 * Two compiler-graph quirks are handled here:
 *
 *  1. NodeNext `.js` specifiers that resolve to `.ts` sources.
 *     The compiler is authored with `import './foo.js'` statements that actually
 *     point at `./foo.ts` (NodeNext convention). esbuild does NOT rewrite these
 *     by default, so the `resolveTsJsPlugin` below remaps `*.js` → `*.ts` (and
 *     `*.js` → `*.jsx`/index variants) whenever the TypeScript source exists.
 *     Generated Peggy `parser.js` files are REAL `.js` files in the tree, so the
 *     plugin only rewrites when a sibling `.ts` exists — leaving `parser.js`
 *     resolution to esbuild's default behaviour.
 *
 *  2. The Peggy `parser.js` files must exist BEFORE bundling.
 *     They are generated by `pnpm build:grammars` into `src/diagrams/<kind>/`.
 *     Because we bundle from `src/` (not `dist/`), esbuild inlines them directly
 *     and we sidestep the `tsc`-doesn't-copy-parser.js dist-sync hack entirely.
 *     This script runs `pnpm build:grammars` in the repo root first, then fails
 *     loudly if any expected `parser.js` is still missing.
 */

import { build, context } from 'esbuild';
import { spawnSync } from 'node:child_process';
import { existsSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url)); // extension/
const repoRoot = resolve(here, '..'); // repo root
const watch = process.argv.includes('--watch');

// ── Precondition: generate the Peggy parsers ───────────────────────────────────
// Bundling from src/ means the generated parser.js files are inlined directly —
// but they only exist after `pnpm build:grammars`. Run it first, then verify.
function ensureGrammars() {
  console.log('› build:grammars (generating Peggy parsers)…');
  const r = spawnSync('pnpm', ['build:grammars'], {
    cwd: repoRoot,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });
  if (r.status !== 0) {
    console.error(
      '\n✗ `pnpm build:grammars` failed. Run it manually in the repo root, then rebuild the extension.',
    );
    process.exit(1);
  }

  // Verify every diagram dir that has a grammar.peggy also has a parser.js.
  const diagramsDir = join(repoRoot, 'src', 'diagrams');
  const missing = [];
  for (const d of readdirSync(diagramsDir)) {
    const dir = join(diagramsDir, d);
    if (!statSync(dir).isDirectory()) continue;
    if (existsSync(join(dir, 'grammar.peggy')) && !existsSync(join(dir, 'parser.js'))) {
      missing.push(`src/diagrams/${d}/parser.js`);
    }
  }
  if (missing.length > 0) {
    console.error(
      `\n✗ Missing generated parser(s) after build:grammars:\n  ${missing.join('\n  ')}\n` +
        '  The esbuild bundle requires these. Re-run `pnpm build:grammars` in the repo root.',
    );
    process.exit(1);
  }
}

// ── Plugin: rewrite NodeNext `*.js` specifiers to the real `*.ts` source ────────
const resolveTsJsPlugin = {
  name: 'resolve-ts-from-js',
  setup(b) {
    // Only relative specifiers ending in `.js` are candidates.
    b.onResolve({ filter: /\.js$/ }, (args) => {
      if (args.kind === 'entry-point') return undefined;
      if (!args.path.startsWith('.')) return undefined; // skip bare/node imports

      const abs = resolve(args.resolveDir, args.path);
      const tsCandidate = abs.replace(/\.js$/, '.ts');
      if (existsSync(tsCandidate)) {
        return { path: tsCandidate };
      }
      // `import './dir/index.js'` style where the source is `.tsx`.
      const tsxCandidate = abs.replace(/\.js$/, '.tsx');
      if (existsSync(tsxCandidate)) {
        return { path: tsxCandidate };
      }
      // Leave everything else (incl. real generated parser.js) to esbuild.
      return undefined;
    });
  },
};

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [join(here, 'src', 'extension.ts')],
  outfile: join(here, 'dist', 'extension.cjs'),
  bundle: true,
  format: 'cjs',
  platform: 'node',
  target: 'node20',
  external: ['vscode'],
  sourcemap: true,
  logLevel: 'info',
  plugins: [resolveTsJsPlugin],
};

ensureGrammars();

if (watch) {
  const ctx = await context(options);
  await ctx.watch();
  console.log('› watching for changes…');
} else {
  await build(options);
  console.log('✓ bundled extension/dist/extension.cjs');
}
