/**
 * esbuild bundle for the Triton VS Code extension.
 *
 * Bundles `extension/src/extension.ts` plus the entire Triton compiler graph
 * (imported by relative path from `../src/**`) into a single CommonJS file at
 * `extension/dist/extension.cjs`. The VS Code extension host loads this via
 * `require()`, so the output MUST be CJS and `vscode` MUST stay external (it is
 * provided by the host and can never be bundled).
 *
 * Two compiler-graph quirks are handled here:
 *
 *  1. NodeNext `.js` specifiers that resolve to `.ts` sources.
 *     The compiler is authored with `import './foo.js'` statements that actually
 *     point at `./foo.ts` (NodeNext convention). esbuild does NOT rewrite these
 *     by default, so the `resolveTsJsPlugin` below remaps `*.js` → `*.ts` (and
 *     `*.js` → `*.jsx`/index variants) whenever the TypeScript source exists.
 *     Generated Peggy `parser.js` files are REAL `.js` files in the tree, so the
 *     plugin only rewrites when a sibling `.ts` exists — leaving `parser.js`
 *     resolution to esbuild's default behaviour.
 *
 *  2. The Peggy `parser.js` files must exist BEFORE bundling.
 *     They are generated by `pnpm build:grammars` into `src/diagrams/<kind>/`.
 *     Because we bundle from `src/` (not `dist/`), esbuild inlines them directly
 *     and we sidestep the `tsc`-doesn't-copy-parser.js dist-sync hack entirely.
 *     This script runs `pnpm build:grammars` in the repo root first, then fails
 *     loudly if any expected `parser.js` is still missing.
 */

import { build, context } from 'esbuild';
import { spawnSync } from 'node:child_process';
import { existsSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url)); // extension/
const repoRoot = resolve(here, '..'); // repo root
const watch = process.argv.includes('--watch');

// ── Precondition: generate the Peggy parsers (incrementally) ────────────────────
// Bundling from src/ means the generated parser.js files are inlined directly —
// but they only exist after the grammars are built. Regenerating all 23 grammars
// on every bundle is the slow path (and shelling out to `pnpm` adds process
// startup + sandbox-prompt overhead), so we ONLY run the generator when a
// `grammar.peggy` is newer than its `parser.js` (or the parser is missing).
// When you edit only `extension.ts`, this skips entirely and the bundle is ~100ms.
function ensureGrammars() {
  const diagramsDir = join(repoRoot, 'src', 'diagrams');

  // Recursively collect every directory under src/diagrams/ holding a
  // `grammar.peggy` (any depth — families may be grouped under a parent such as
  // src/diagrams/ds/<family>/). Mirrors scripts/build-grammars.mjs discovery.
  function findGrammarDirs(dir) {
    const out = [];
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const sub = join(dir, entry.name);
      if (existsSync(join(sub, 'grammar.peggy'))) out.push(sub);
      out.push(...findGrammarDirs(sub));
    }
    return out;
  }

  const stale = [];
  for (const dir of findGrammarDirs(diagramsDir)) {
    const grammar = join(dir, 'grammar.peggy');
    const parser = join(dir, 'parser.js');
    if (!existsSync(parser) || statSync(parser).mtimeMs < statSync(grammar).mtimeMs) {
      stale.push(relative(diagramsDir, dir)); // e.g. "ds/tree" or "flowchart"
    }
  }

  if (stale.length === 0) {
    console.log('› parsers up to date — skipping build:grammars');
    return;
  }

  console.log(`› build:grammars (${stale.length} stale: ${stale.join(', ')})…`);
  // Call the generator directly with `node` — avoids pnpm startup + sandbox prompts.
  const r = spawnSync(process.execPath, [join(repoRoot, 'scripts', 'build-grammars.mjs')], {
    cwd: repoRoot,
    stdio: 'inherit',
  });
  if (r.status !== 0) {
    console.error(
      '\n✗ build-grammars.mjs failed. Run `pnpm build:grammars` in the repo root, then rebuild.',
    );
    process.exit(1);
  }

  const missing = stale.filter((d) => !existsSync(join(diagramsDir, d, 'parser.js')));
  if (missing.length > 0) {
    console.error(
      `\n✗ Missing generated parser(s) after build:grammars:\n  ${missing
        .map((d) => `src/diagrams/${d}/parser.js`)
        .join('\n  ')}`,
    );
    process.exit(1);
  }
}

// ── Plugin: rewrite NodeNext `*.js` specifiers to the real `*.ts` source ────────
const resolveTsJsPlugin = {
  name: 'resolve-ts-from-js',
  setup(b) {
    // Only relative specifiers ending in `.js` are candidates.
    b.onResolve({ filter: /\.js$/ }, (args) => {
      if (args.kind === 'entry-point') return undefined;
      if (!args.path.startsWith('.')) return undefined; // skip bare/node imports

      const abs = resolve(args.resolveDir, args.path);
      const tsCandidate = abs.replace(/\.js$/, '.ts');
      if (existsSync(tsCandidate)) {
        return { path: tsCandidate };
      }
      // `import './dir/index.js'` style where the source is `.tsx`.
      const tsxCandidate = abs.replace(/\.js$/, '.tsx');
      if (existsSync(tsxCandidate)) {
        return { path: tsxCandidate };
      }
      // Leave everything else (incl. real generated parser.js) to esbuild.
      return undefined;
    });
  },
};

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [join(here, 'src', 'extension.ts')],
  outfile: join(here, 'dist', 'extension.cjs'),
  bundle: true,
  format: 'cjs',
  platform: 'node',
  target: 'node20',
  external: ['vscode'],
  sourcemap: true,
  logLevel: 'info',
  plugins: [resolveTsJsPlugin],
};

ensureGrammars();

if (watch) {
  const ctx = await context(options);
  // Guarantee a fresh bundle BEFORE entering watch mode, so the extension host
  // never loads a stale dist/extension.cjs (e.g. after pulling new diagram kinds).
  await ctx.rebuild();
  console.log('✓ bundled extension/dist/extension.cjs');
  await ctx.watch();
  console.log('› watching for changes…');
} else {
  await build(options);
  console.log('✓ bundled extension/dist/extension.cjs');
}
