/**
 * esbuild bundle for the Triton → LaTeX CLI (`@triton/latex`).
 *
 * Bundles `latex/src/cli.ts` plus the entire Triton compiler graph (imported by
 * relative path from `../src/**`) into a single CommonJS file at
 * `latex/dist/cli.cjs`. The CLI is invoked with `node dist/cli.cjs` (or via the
 * `triton-latex` bin), so the output MUST be CJS.
 *
 * The PDF toolchain (`pdfkit`, `svg-to-pdfkit`) is kept EXTERNAL — it is resolved
 * from `latex/node_modules` at runtime. This is what keeps those dependencies
 * OUT of the core `triton` package: they live here and only here.
 *
 * This mirrors `extension/esbuild.mjs` and handles the same two compiler-graph
 * quirks:
 *
 *  1. NodeNext `.js` specifiers that resolve to `.ts` sources.
 *     The compiler is authored with `import './foo.js'` statements that actually
 *     point at `./foo.ts`. esbuild does NOT rewrite these by default, so the
 *     `resolveTsJsPlugin` remaps `*.js` → `*.ts`/`*.tsx` whenever the TypeScript
 *     source exists. Generated Peggy `parser.js` files are REAL `.js` files, so
 *     the plugin only rewrites when a sibling `.ts` exists.
 *
 *  2. The Peggy `parser.js` files must exist BEFORE bundling.
 *     They are generated by the grammar build into `src/diagrams/<kind>/`.
 *     Because we bundle from `src/` (not `dist/`), esbuild inlines them directly.
 *     This script runs the generator (incrementally) first, then fails loudly if
 *     any expected `parser.js` is still missing.
 */

import { build, context } from 'esbuild';
import { spawnSync } from 'node:child_process';
import { existsSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url)); // latex/
const repoRoot = resolve(here, '..'); // repo root
const watch = process.argv.includes('--watch');

// ── Precondition: generate the Peggy parsers (incrementally) ────────────────────
// Bundling from src/ means the generated parser.js files are inlined directly —
// but they only exist after the grammars are built. We ONLY run the generator
// when a `grammar.peggy` is newer than its `parser.js` (or the parser is missing).
function ensureGrammars() {
  const diagramsDir = join(repoRoot, 'src', 'diagrams');

  function findGrammarDirs(dir) {
    const out = [];
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const sub = join(dir, entry.name);
      if (existsSync(join(sub, 'grammar.peggy'))) out.push(sub);
      out.push(...findGrammarDirs(sub));
    }
    return out;
  }

  const stale = [];
  for (const dir of findGrammarDirs(diagramsDir)) {
    const grammar = join(dir, 'grammar.peggy');
    const parser = join(dir, 'parser.js');
    if (!existsSync(parser) || statSync(parser).mtimeMs < statSync(grammar).mtimeMs) {
      stale.push(relative(diagramsDir, dir));
    }
  }

  if (stale.length === 0) {
    console.log('› parsers up to date — skipping build:grammars');
    return;
  }

  console.log(`› build:grammars (${stale.length} stale: ${stale.join(', ')})…`);
  // Call the generator directly with `node` — avoids pnpm startup + sandbox prompts.
  const r = spawnSync(process.execPath, [join(repoRoot, 'scripts', 'build-grammars.mjs')], {
    cwd: repoRoot,
    stdio: 'inherit',
  });
  if (r.status !== 0) {
    console.error(
      '\n✗ build-grammars.mjs failed. Run `pnpm build:grammars` in the repo root, then rebuild.',
    );
    process.exit(1);
  }

  const missing = stale.filter((d) => !existsSync(join(diagramsDir, d, 'parser.js')));
  if (missing.length > 0) {
    console.error(
      `\n✗ Missing generated parser(s) after build:grammars:\n  ${missing
        .map((d) => `src/diagrams/${d}/parser.js`)
        .join('\n  ')}`,
    );
    process.exit(1);
  }
}

// ── Plugin: rewrite NodeNext `*.js` specifiers to the real `*.ts` source ────────
const resolveTsJsPlugin = {
  name: 'resolve-ts-from-js',
  setup(b) {
    b.onResolve({ filter: /\.js$/ }, (args) => {
      if (args.kind === 'entry-point') return undefined;
      if (!args.path.startsWith('.')) return undefined; // skip bare/node imports

      const abs = resolve(args.resolveDir, args.path);
      const tsCandidate = abs.replace(/\.js$/, '.ts');
      if (existsSync(tsCandidate)) {
        return { path: tsCandidate };
      }
      const tsxCandidate = abs.replace(/\.js$/, '.tsx');
      if (existsSync(tsxCandidate)) {
        return { path: tsxCandidate };
      }
      // Leave everything else (incl. real generated parser.js) to esbuild.
      return undefined;
    });
  },
};

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [join(here, 'src', 'cli.ts')],
  outfile: join(here, 'dist', 'cli.cjs'),
  bundle: true,
  format: 'cjs',
  platform: 'node',
  target: 'node20',
  // The PDF toolchain stays external — resolved from latex/node_modules at
  // runtime. This is what keeps these deps OUT of the core triton package.
  external: ['pdfkit', 'svg-to-pdfkit'],
  banner: { js: '#!/usr/bin/env node' },
  sourcemap: true,
  logLevel: 'info',
  plugins: [resolveTsJsPlugin],
};

ensureGrammars();

if (watch) {
  const ctx = await context(options);
  await ctx.rebuild();
  console.log('✓ bundled latex/dist/cli.cjs');
  await ctx.watch();
  console.log('› watching for changes…');
} else {
  await build(options);
  console.log('✓ bundled latex/dist/cli.cjs');
}
