---
title: Distributed Systems Concepts
theme: dark-tree
---
mindmap
  root((Distributed Systems))
    Consensus
      Raft
      ::icon(fa fa-check)
      Paxos
      ZAB
    Communication
      RPC
        gRPC
        REST
      Messaging
        Kafka
        ::icon(fa fa-stream)
        RabbitMQ
    Storage
      Relational
        PostgreSQL
        MySQL
      NoSQL
        MongoDB
        Cassandra
        Redis
        ::icon(fa fa-database)
    Observability
      Metrics
        Prometheus
      Tracing
        Jaeger
        Zipkin
      Logging
        ELK Stack
