topology
  title NUMA node detail
  costs ns
    tier local 90 #27ae60
    tier remote 200 #e2574c 5 4
  group N0 : NUMA Node 0
    node C0 : Core 0
    node C1 : Core 1
    node MC0 : Mem Ctrl
    node RAM0 : Local DRAM : 64 GB
  group N1 : NUMA Node 1
    node C2 : Core 2
    node C3 : Core 3
    node MC1 : Mem Ctrl
    node RAM1 : Local DRAM : 64 GB
  MC0 -- RAM0 : 90
  MC1 -- RAM1 : 90
  N0 -- N1 : 140
  MC0 -- RAM1 : 200
